version: '3.7'
services:
  nestchat:
    depends_on:
      - postgres
    links:
      - postgres:postgres
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=dev
    image: nest-chat-docker
    container_name: nestchat
    restart: always
    tty: true
    ports:
      - 3000:3000
    working_dir: /var/www/nest-chat
    environment:
      - NODE_ENV=development
      - NODE_PORT=3001
      - JWT_SECRET=TopSecretHighlyClassified=D
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123456
      - DATABASE_NAME=vapulus
      - TYPEORM_SYNC=true
      - TYPEORM_ENTITIES=**/*.entity{.ts,.js}
      - TYPEORM_MIGRATIONS=db/migrations/*{.ts,.js}
      - TYPEORM_MIGRATIONS_RUN=src/db/migrations
      - TYPEORM_MIGRATIONS_DIR=src/db/migrations
      - TYPEORM_LOGGING=true
      - TYPEORM_MAX_QUERY_EXECUTION_TIME=1000

    volumes:
      - ./:/var/www/nest-chat
      - /var/www/nest-chat/node_modules
    networks:
      - nest-chat-network
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=vapulus
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123456
    networks:
      - nest-chat-network

networks:
  nest-chat-network:
    driver: bridge
volumes:
  post_data: { }
